services:
  app:
    build: .
    container_name: djangoagenda
    command: "uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload --reload-include *"
    ports: 
      - 8000:8000
    volumes:
      - .:/usr/src/app