# Generated by Django 4.1.5 on 2023-02-01 14:42

import core.rules
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evento_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraRepeticao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_regra', models.IntegerField(choices=[(core.regras.regras.TipoRepeticao['NAO_REPETE'], 1), (
                core.regras.regras.TipoRepeticao['TODO_DIA'], 2), (core.regras.regras.TipoRepeticao['TODA_SEMANA'], 3), (
                                                            core.regras.regras.TipoRepeticao['TODO_ANO'], 4), (
                                                            core.regras.regras.TipoRepeticao['TODO_DIA_DE_SEMANA'], 5), (
                                                            core.regras.regras.TipoRepeticao['TODO_PERIODO'], 6)])),
                ('vezes', models.IntegerField(default=-1)),
                ('periodo', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='regra_repeticao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.regrarepeticao'),
        ),
    ]
